# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4563c77bc1d9dc6fa8c478d19d637b4d2c5d2de380323027749227a0ed0fa5bda6487c586f3c4416a916011cc05844f9755b43b40ef444375883f7371f47d347

test:
  secret_key_base: 48a3dfaad56f94741a51f980866cab1474c4c271934c21958678018145c576f1de2a5ba8639464b6fa09226b5d219e735e58a1702c51349b93a1f53e65fe75e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
